# -- Terminal Theme Parameters --
# https://github.com/panr/hugo-theme-terminal

# dir name of your main content (default is `content/posts`)
contentTypeName = "posts"

# ["orange", "blue", "red", "green", "pink"]
themeColor = "blue"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 0

# show selector to switch language
showLanguageSelector = false

# set theme to full screen width
fullWidthTheme = true

# center theme with default width
centerTheme = false

# if your resource directory contains an image called `cover.(jpg|png|webp)`,
# then the file will be used as a cover automatically.
# With this option you don't have to put the `cover` param in a front-matter.
autoCover = true

# set post to show the last updated
# If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
showLastUpdated = false

# set a custom favicon (default is a `themeColor` square)
# favicon = "favicon.ico"

# Custom CSS - Terminal theme uses static/style.css automatically

# Site copyright
copyright = "© 1996-2025 David Laing"

# Logo configuration (try at top level)
[logo]
logoText = "mrdavidlaing@🌍:~$"
logoHomeLink = "/"

# Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
# updatedDatePrefix = "Updated"

[params.twitter]
# set Twitter handles for Twitter cards
# see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
# do not include @
creator = ""
site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "mrdavidlaing@🌍:~$"
    subtitle = "Staff Developer & Full Stack Engineer"
    owner = ""
    keywords = ""
    copyright = "ⓒ 1996-2025 David Laing"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "mrdavidlaing@🌍:~$"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "cv"
        name = "cv"
        url = "/cv"